### PR TITLE
Latest vmmlib API

### PR DESCRIPTION
**Pull request by eile**

### CODE REVIEW

**Comment by jafyvilla** [comment]
+1

**Comment by eile** [comment]
Retest this please.

**Comment by eile** [comment]
@jafyvilla : Is the test failure related to the TestData update? I don't think the vmml change can cause this.

**Comment by jafyvilla** [comment]
@eile the failure is because of this https://bbpcode.epfl.ch/code/#/c/21822/

I have changed the test in Fivox, and I will push it to #10

**Comment by jafyvilla** [comment]
Actually, if you just update the expected value in the test and push it here it should be fine for now. My tests are totally different anyway, as many things are changing in the loaders/functors.

**Comment by hernando** [comment]
Retest this please

**Comment by hernando** [comment]
This is failing because the SHA1 reference to vmmlib doesn't exist.

**Pull request merged**
