### PR TITLE
Compilation fixes after recents changes in Brion

### PR DESCRIPTION
**Pull request by hernando**

### CODE REVIEW

**Comment by tribal-tec** [comment]
Missing update of Brion SHA-1

**Comment by tribal-tec** [comment]
+1 otherwise, obviously :)

**Comment by hernando** [comment]
I don't get why this is still failing. Let's see if after the Livre PR is merged this can be fixed.

**Comment by tribal-tec** [comment]
CMake/common SHA-1 too old IIRC (saw this error before)

**Pull request merged**
